# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: nandakke_development
  username: nand_development
  password: pass_development

test:
 <<: *default
 database: nandakke_test
 username: nand_test
 password: pass_test

production:
 <<: *default
 database: nandakke_production
 username: nand_production
 password: pass_production
